version: '3.0'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env.local
    ports:
      - 5432:5432